package org.yidu.novel.entity;

// Generated 2013/12/26 20:57:47 by Hibernate Tools 3.4.0.CR1

/**
 * TSystemConfig generated by hbm2java
 */
public class TSystemConfig implements java.io.Serializable {

    private static final long serialVersionUID = 1896384275550616445L;
    private int configno;
    private String name;
    private String title;
    private String description;
    private Short type;
    private String options;
    private String catname;

    public TSystemConfig() {
    }

    public TSystemConfig(int configno) {
        this.configno = configno;
    }

    public TSystemConfig(int configno, String name, String title, String description, Short type, String options,
            String catname) {
        this.configno = configno;
        this.name = name;
        this.title = title;
        this.description = description;
        this.type = type;
        this.options = options;
        this.catname = catname;
    }

    public int getConfigno() {
        return this.configno;
    }

    public void setConfigno(int configno) {
        this.configno = configno;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Short getType() {
        return this.type;
    }

    public void setType(Short type) {
        this.type = type;
    }

    public String getOptions() {
        return this.options;
    }

    public void setOptions(String options) {
        this.options = options;
    }

    public String getCatname() {
        return this.catname;
    }

    public void setCatname(String catname) {
        this.catname = catname;
    }

}
