package org.yidu.novel.entity;

// Generated 2013/12/26 20:57:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

    private static final long serialVersionUID = 8319861322717026182L;
    private int userno;
    private String loginid;
    private String password;
    private String username;
    private String email;
    private Date regdate;
    private Short sex;
    private String qq;
    private Date lastlogin;
    private String lineno;
    private Short type;
    private Integer votecount;
    private Boolean deleteflag;
    private String realname;
    private String id;
    private String mobileno;
    private String branch;
    private String bankno;
    private String alipayacount;

    public TUser() {
    }

    public TUser(int userno, String loginid, String username) {
        this.userno = userno;
        this.loginid = loginid;
        this.username = username;
    }

    public TUser(int userno, String loginid, String password, String username, String email, Date regdate, Short sex,
            String qq, Date lastlogin, String lineno, Short type, Integer votecount, Boolean deleteflag,
            String realname, String id, String mobileno, String branch, String bankno, String alipayacount) {
        this.userno = userno;
        this.loginid = loginid;
        this.password = password;
        this.username = username;
        this.email = email;
        this.regdate = regdate;
        this.sex = sex;
        this.qq = qq;
        this.lastlogin = lastlogin;
        this.lineno = lineno;
        this.type = type;
        this.votecount = votecount;
        this.deleteflag = deleteflag;
        this.realname = realname;
        this.id = id;
        this.mobileno = mobileno;
        this.branch = branch;
        this.bankno = bankno;
        this.alipayacount = alipayacount;
    }

    public int getUserno() {
        return this.userno;
    }

    public void setUserno(int userno) {
        this.userno = userno;
    }

    public String getLoginid() {
        return this.loginid;
    }

    public void setLoginid(String loginid) {
        this.loginid = loginid;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getRegdate() {
        return this.regdate;
    }

    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    public Short getSex() {
        return this.sex;
    }

    public void setSex(Short sex) {
        this.sex = sex;
    }

    public String getQq() {
        return this.qq;
    }

    public void setQq(String qq) {
        this.qq = qq;
    }

    public Date getLastlogin() {
        return this.lastlogin;
    }

    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }

    public String getLineno() {
        return this.lineno;
    }

    public void setLineno(String lineno) {
        this.lineno = lineno;
    }

    public Short getType() {
        return this.type;
    }

    public void setType(Short type) {
        this.type = type;
    }

    public Integer getVotecount() {
        return this.votecount;
    }

    public void setVotecount(Integer votecount) {
        this.votecount = votecount;
    }

    public Boolean getDeleteflag() {
        return deleteflag;
    }

    public void setDeleteflag(Boolean deleteflag) {
        this.deleteflag = deleteflag;
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMobileno() {
        return mobileno;
    }

    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }

    public String getBranch() {
        return branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public String getBankno() {
        return bankno;
    }

    public void setBankno(String bankno) {
        this.bankno = bankno;
    }

    public String getAlipayacount() {
        return alipayacount;
    }

    public void setAlipayacount(String alipayacount) {
        this.alipayacount = alipayacount;
    }

}
