document.writeln("<div style=\"width:960px; overflow:hidden;\">");
document.writeln("<script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"></script>");
document.writeln("<!-- 站群小说阅读页广告1 -->");
document.writeln("<ins class=\"adsbygoogle\"");
document.writeln("     style=\"display:inline-block;width:970px;height:90px\"");
document.writeln("     data-ad-client=\"ca-pub-0918341902931277\"");
document.writeln("     data-ad-slot=\"2691199547\"></ins>");
document.writeln("<script>");
document.writeln("(adsbygoogle = window.adsbygoogle || []).push({});");
document.writeln("</script>");
document.writeln("</div>");